// <auto-generated />
namespace SUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MaestroDetalle_Ventas1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaestroDetalle_Ventas1));
        
        string IMigrationMetadata.Id
        {
            get { return "201805290423281_MaestroDetalle_Ventas1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
