// <auto-generated />
namespace SUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modificacion_Relaciones_Inventario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modificacion_Relaciones_Inventario));
        
        string IMigrationMetadata.Id
        {
            get { return "201805020640139_Modificacion_Relaciones_Inventario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
