// <auto-generated />
namespace SUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CellarProducts_Stock_double : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CellarProducts_Stock_double));
        
        string IMigrationMetadata.Id
        {
            get { return "201805302004316_CellarProducts_Stock_double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
